export const SCRIPT = [
  'two bottles',
  'a Lays packet',
  'no, make that three',
  'another one',
  'two cups and a can',
  'scratch that',
  'a Bisleri bottle',
  'four cigarette butts',
  'a Kurkure packet',
  'one Frooti',
  'a couple of wrappers',
  'a few cans',
  'sorry, two',
  'I mean a glass bottle',
  'eight bottle caps',
  'a plastic bag',
  'half a dozen cigarette ends',
  'a juice box',
  'one more',
  'undo',
  'a coffee cup and two wrappers',
  'excuse me, sorry',
  'three cartons',
  'a newspaper',
  'ignore that',
  'a beer bottle',
  'two more',
  'a crisp packet',
  'a dozen bottle tops',
  'nice weather today',
]
